#ifndef PLUGIN_EXECUTE_RESOURCES_H_INCLUDED
#define PLUGIN_EXECUTE_RESOURCES_H_INCLUDED

#define ID_DIALOG_CONFIG   1

#define ID_EDIT_RUN			0x401
#define ID_EDIT_WORK_DIR	0x402

#define ID_BUTTON_OK		0x101
#define ID_BUTTON_CANCEL	0x102
#define ID_BROWSE_RUN		0x120
#define ID_BROWSE_WORK_DIR	0x121

#define ON_ITEM_SELECT (( LBN_SELCHANGE )<<16)
#define ON_CLICK       (( BN_CLICKED    )<<16)
#define ON_CHANGE      (( EN_CHANGE     )<<16)

#endif // PLUGIN_EXECUTE_RESOURCES_H_INCLUDED
