#ifndef PLUGIN_HTTP_RESOURCES_H_INCLUDED
#define PLUGIN_HTTP_RESOURCES_H_INCLUDED

#define ID_DIALOG_CONFIG   1

#define ID_EDIT_IP_ADDRESS		0x401
#define ID_EDIT_PORT			0x402
#define ID_EDIT_SCRIPT			0x403

#define ID_BUTTON_OK			0x101
#define ID_BUTTON_CANCEL		0x102

#define ID_GROUPBOX_SERVER		0x201

#define ON_ITEM_SELECT (( LBN_SELCHANGE )<<16)
#define ON_CLICK       (( BN_CLICKED    )<<16)
#define ON_CHANGE      (( EN_CHANGE     )<<16)

#endif // PLUGIN_HTTP_RESOURCES_H_INCLUDED
